### ISSUE TITLE
plz add allowInsecureProtocol

### ISSUE THREAD

**Issue by hnry33** [blinkcard/blinkcard-flutter#10]
> Using insecure protocols with repositories, without explicit opt-in, is unsupported. Switch Maven repository 'maven3(http://maven.microblink.com)' to redirect to a secure protocol (like HTTPS) or allow insecure protocols. See https://docs.gradle.org/7.4.2/dsl/org.gradle.api.artifacts.repositories.UrlArtifactRepository.html#org.gradle.api.artifacts.repositories.UrlArtifactRepository:allowInsecureProtocol for more details. 
[        ] * Try:
[        ] > Run with --stacktrace option to get the stack trace.
[        ] > Run with --info or --debug option to get more log output.
[        ] > Run with --scan to get full insights.
[        ] * Get more help at https://help.gradle.org
[        ] BUILD FAILED in 3s

**Comment by krizaa** [comment]
Hi, thanks for pointing this out. We fixed this issue in BlinkCard v2.6.0 🎉
