### ISSUE TITLE
Namespace not specified Gradle 8.2.2

### ISSUE THREAD

**Issue by Tareq-Ghassan** [blinkcard/blinkcard-flutter#16]
Hello,

I'm encountering the following exception due to the recent Gradle update 8.2.2, which now requires the namespace to be specified in the Gradle file rather than in the Manifest.

`FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':blinkcard_flutter'.
> Could not create an instance of type com.android.build.api.variant.impl.LibraryVariantBuilderImpl.
   > Namespace not specified. Specify a namespace in the module's build file. See https://d.android.com/r/tools/upgrade-assistant/set-namespace for information about setting the namespace.
     
     If you've specified the package attribute in the source AndroidManifest.xml, you can use the AGP Upgrade Assistant to migrate to the namespace value in the build file. Refer to https://d.android.com/r/tools/upgrade-assistant/agp-upgrade-assistant for general information about using the AGP Upgrade Assistant.

* Try:
> Run with --info or --debug option to get more log output.
> Get more help at https://help.gradle.org.`

**Please address this issue promptly as it is preventing us from releasing our app.**

**Comment by mparadina** [comment]
Hi @Tareq-Ghassan 

Thank you for waiting.
We will fix the mentioned issue with the next release of the SDK, 2.9.1, which should be released by the end of next week.

**Comment by mparadina** [comment]
Hi @Tareq-Ghassan 

We've released BlinkCard 2.9.1, which contains the namespace property in the `build.gradle` file.
You can test it out and let us know if it is working as expected now?

**Comment by Tareq-Ghassan** [comment]
Hi @mparadina 
I've tested BlinkCard 2.9.1, and it works fine. Everything is functioning as expected

**Comment by Tareq-Ghassan** [comment]
Hi @mparadina
I've tested BlinkCard 2.9.1, and it works fine. Everything is functioning as expected
