### ISSUE TITLE
Setting the namespace via the package attribute in the source AndroidManifest.xml is no longer supported

### ISSUE THREAD

**Issue by omartinma** [blinkcard/blinkcard-flutter#19]
As confirmed via email with the support team on this package we will have the same issue described here for BlinkID package https://github.com/BlinkID/blinkid-flutter/issues/62

**Comment by somyaguptagit** [comment]
Hi @omartinma Thank you for your inquiry!
 Could you please confirm if you are running into the same issue on the BlinkCard-flutter platform?

**Comment by omartinma** [comment]
In my email thread your team confirmed was an issue. Anyway with your latest release have been fixed, so we can close this ticket. @somyaguptagit. Thanks!
