### ISSUE TITLE
Your license key is invalid! License has expired on 2021-12-02

### ISSUE THREAD

**Issue by jblis2bfortu** [blinkcard/blinkcard-flutter#6]
Hello, only in ios don't read any card and show this message in the console:

[E] func [line::262] Your license key is invalid! License has expired on 2021-12-02

Android is ok

obs: I'm using a trial license that comes pre-defined in the example app

**Comment by mparadina** [comment]
Hi @jblis2bfortu 

The mentioned message indicates that the license key entered in the project has expired.
A valid license key is necessary for the SDK to properly work and initialise the scanning process.

I suggest contacting us directly at support@microblink.com to further discuss the inquiry.

**Comment by jblis2bfortu** [comment]
Ok thanks!
