### ISSUE TITLE
Can't control all overlay messages.

### ISSUE THREAD

**Issue by nadas00** [blinkcard/blinkcard-flutter#7]
Hİ,

There are firstSideInstructions ,flipCardInstructions fields only in BlinkCardOverlaySettings. For example how can I change  [[blinkcard_overlay_camera_too_near_message]] or [[blinkcard_overlay_identification_field_message]] messages? How can I populate the options?

An example with a fake credit card.
![IMG_2198](https://user-images.githubusercontent.com/46631211/152354646-18684039-3f1e-4768-a578-18106b671d91.jpg)

**Comment by anjapenic** [comment]
Hello @nadas00,

Is your device language set to other than English and if so, which one? Is this issue occurring with all strings or just these two [[blinkcard_overlay_camera_too_near_message]] and [[blinkcard_overlay_identification_field_message]]?

Best regards,
Anja

**Comment by nadas00** [comment]
@anjapenic 
Hi, my device is Turkish but It is not the problem I want to point out. I want to give custom text for overlay settings but only option for that  "String? firstSideInstructions;", " String? flipCardInstructions;" in BlinkCardOverlaySettings class. 

I was expecting "String? cameraTooNearMessage;" , "String? overlay_identification_field_message" and so. There are no specific fields for that options. firstSideInstructions, flipCardInstructions exists and work well but other messages are not customizable.

**Comment by anjapenic** [comment]
Hello @nadas00,

BlinkCard has only these 4 customizable strings - firstSideInstructions, flipCardInstructions, glareMessage and manualEntryMessage. 

Regarding the second issue, could you share with us how exactly are you setting the language?

Best regards,
Anja

**Comment by nadas00** [comment]
@anjapenic Thank you for your helps.  I hope customizable string options will be inclusive in future. I solved second issue somehow.
